### ISSUE TITLE
The function conflict between addNodeJunction and closeNetwork!!

### ISSUE THREAD

**Issue by lookforhan** [KIOS-Research/CCWI2016#4]
The matlab will crash when the addNodeJunction and closeNetwork run in sequence, as follows:
`
d = epanet('Net1.inp');
  
d.addNodeJunction('j1');  

d.closeNetwork;
`

**Comment by Mariosmsk** [comment]
Hi @lookforhan,

EPANET-Matlab-Toolkit updates/releases: 

https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit

https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/releases

Now we are working on branch `dev-2.2-edit` you can download from [here](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/archive/dev-2.2-edit.zip) to test.

**Comment by lookforhan** [comment]
Hi @Mariosmsk,
Thanks for your replying.
I have downloaded and tested the dev-2.2-edit, while the conflict still exists.
